hibernate.connection.driver_class=org.postgressql.Driver
hibernate.connection.url=jdbc:postgressql://localhost:5432/avaliacao1
hibernate.connection.username=postgres
hibernate.connection.password=2006

hibernate.dialect=org.hibernate.dialect.PostgresSQLDialect

hibernate.show_sql=true
hibernate.format_sql=true

hibernate.hbm2dd1.auto=update